### ISSUE TITLE
Can't generate more thank 10 NFT in edition.

### ISSUE THREAD

**Issue by guramxatiashvili** [HashLips/generative-art-opensource#22]
I'm getting the following error after changing 'editionSize' variable to 100 in 'config.js' - 

Create your NFT collection
##################

start creating NFTs.
-----------------
creating NFT 1 of 100
- rarity: undefined
(node:16612) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at /Users/gukha/Desktop/IdeaProjects/generative-art-opensource/index.js:133:77
    at Array.forEach (<anonymous>)
    at createDna (/Users/gukha/Desktop/IdeaProjects/generative-art-opensource/index.js:132:11)
    at startCreating (/Users/gukha/Desktop/IdeaProjects/generative-art-opensource/index.js:200:18)
    at Object.<anonymous> (/Users/gukha/Desktop/IdeaProjects/generative-art-opensource/index.js:249:1)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:16612) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:16612) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by designworkplan** [comment]
Encountered the same issue. Did anyone else run into this issue? Cheers.

**Comment by Ponda1** [comment]
This issue means something is wrong with the edition values in the config file. Check the edition values and rarityWeights and make sure they are correct. For example, if I wanna make 100 editions then startEditionFrom should be 1 and editionSize should be 100. The rarity weights could be something like (super_rare, 1, 10) , (rare, 11, 49) and (original 50,100).

**Comment by pehcastro** [comment]
check this 

```
let rarityWeights = [
  addRarity('common', 1, 5200),
  addRarity('uncommon', 5200, 8000),
  addRarity('rare', 8000, 9100),
  addRarity('epic', 9100, 9900),
  addRarity('exotic', 9900, 10000),
];
```

were "1" is the start for common rarity going until 5200, and 10000 is where the exotic ends, sou you can have 10k nfts minted with this.

edition size should be 10000 too

**Comment by Ponda1** [comment]
Im a noob but im pretty sure the issue here is that the rarities are not continuous. so your code should look like this instead:

let rarityWeights = [
  addRarity('common', 1, 5200),
  addRarity('uncommon', 5201, 8000),
  addRarity('rare', 8001, 9100),
  addRarity('epic', 9101, 9900),
  addRarity('exotic', 9901, 10000),
];

This should fix the problem

**Comment by keeksthefreeks** [comment]
Howdy! I'm still having problems with this and was hoping someone could help me out. Here is what it kicked out when I switched from 10 to 100

start creating NFTs.
-----------------
creating NFT 1 of 100
- rarity: original
- dna: 04-04-08-03-02-02-08-010-04-02-05-03-03
(node:13231) UnhandledPromiseRejectionWarning: ReferenceError: signImage is not defined
    at /Users/kylelauterbach/Downloads/generative-art-opensource-main/index.js:233:7
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async startCreating (/Users/kylelauterbach/Downloads/generative-art-opensource-main/index.js:220:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:13231) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:13231) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
k@Kyles-MBP generative-art-opensource-main %
